name: Deploy React + Vite on GithHub

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node Js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
        #   node-version: 18
          node-version: 21

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Build the Project
      - name: Build the Project
        run: npm run build

      # Deploy to the GitHub Pages
      - name: Deploy to the GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
